### ISSUE TITLE
No Samples attached for Executing workflows from java code

### ISSUE THREAD

**Issue by jieap2** [googleapis/java-workflow-executions#158]
HI Team,

For using the client libraries, was looking for the samples section and it was empty, i am not sure if it was a miss or intentional.If it can be provided will be really helpful to automate cloud workflows.

@chingor13 @Neenu1995  @JustinBeckwith  can anyone help here?

**Comment by jieap2** [comment]
Is there any help that can be provided just to start with?Appreceiate your help in advance

**Comment by lesv** [comment]
@danoscarmike Do we own this?

**Comment by danoscarmike** [comment]
@lesv by default we own the library, yes.

@jieap2 I'm afraid this is "working as intended" - we are not currently in a position to add detailed samples for this product. 

For a general overview of the API see https://cloud.google.com/workflows/docs/apis (REST reference, etc.). 

Are you familiar with our other Cloud Client Libraries? The general client features and patterns (instantiation etc.) If not, is there a particular use case you are trying to achieve?

**Comment by averikitsch** [comment]
You can find an example of executing a workflow here: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/workflows/cloud-client
